name: Publish
on:
    workflow_dispatch:
        inputs:
            release-type:
                description: "Release type (one of): patch, minor, major"
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Git configuration
              run: |
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "GitHub Actions"

            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: main
                  token: ${{ secrets.AUTH_TOKEN }}

            - name: Install dependencies
              run: npm ci
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            - name: Build
              run: npm run compile
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            - name: Bump release version
              if: startsWith(github.event.inputs.release-type, 'pre') != true
              run: |
                  echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
                  echo "RELEASE_TAG=latest" >> $GITHUB_ENV
              env:
                  RELEASE_TYPE: ${{ github.event.inputs.release-type }}
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            # Commit changes
            - name: Commit package.json changes and create tag
              run: |
                  git add "package.json"
                  git commit -m "chore: release ${{ env.NEW_VERSION }}"
                  git tag ${{ env.NEW_VERSION }}

            - name: Publish package on NPM 📦
              run: npm version ${{ env.RELEASE_TYPE }} && npm publish
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            - name: Push changes to repository
              env:
                  GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
              run: |
                  git push origin && git push --tags

            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

            - name: Update GitHub release documentation
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ env.NEW_VERSION }}
                  body: ${{steps.github_release.outputs.changelog}}
                  prerelease: ${{ startsWith(github.event.inputs.release-type, 'pre') }}
              env:
                  GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
