name: Publish Package to npmjs
on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies and build 🔧
              run: npm ci && npm run compile
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}
            - name: Publish package on NPM 📦
              run: npm publish
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}
