name: Publish
on:
    workflow_dispatch:
        inputs:
            release-type:
                description: "Release type (one of): patch, minor, major"
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies and build 🔧
              run: npm ci && npm run compile
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            - name: Publish package on NPM 📦
              run: npm version "${{ github.event.inputs.release-type }} && npm publish
              env:
                  GITHUB_TOKEN_PACKAGES: ${{ secrets.AUTH_TOKEN }}

            - name: Create and push git tag
              uses: anothrNick/github-tag-action@1.30
              with:
              github_token: ${{ secrets.AUTH_TOKEN }}
              tag: v$(npm --silent version)

            - name: Push changes to the git repository
              uses: ad-m/github-push-action@v0.6.0
              with:
                  github_token: ${{ secrets.AUTH_TOKEN }}
                  branch: master

            - name: Create GitHub release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
              with:
              tag_name: v$(npm --silent version)
              release_name: Release v$(npm --silent version)
              body: |
                  Release v$(npm --silent version)
              draft: false
              prerelease: false
